//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsAppEntityFrameworkDbFirst
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class UrunYonetimiAdoNetEntities : DbContext
    {
        public UrunYonetimiAdoNetEntities()
            : base("name=UrunYonetimiAdoNetEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Kategoriler> Kategoriler { get; set; }// EF de veritabanı tablolarını dbset'lerle ifade ediyoruz 
        public virtual DbSet<Products> Products { get; set; }
    }
}
